# Generated by Django 2.2.7 on 2020-04-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200418_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
