# Generated by Django 2.2.7 on 2020-04-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200420_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
